version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meow
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
