version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meow
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./var/lib/redis/data:/data
    command: [ "redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
